package algo

import (
	"testing"
	"time"

	"github.com/ajitem/fpl-intelligence/internal/fpl"
)

// newsExpectation mirrors one row of testdata/news_expectations.json,
// generated by running the Python implementation over every player in the
// frozen bootstrap.
type newsExpectation struct {
	ID        int     `json:"id"`
	News      string  `json:"news"`
	NewsAdded *string `json:"news_added"`
	Penalty   float64 `json:"penalty"`
	Negative  bool    `json:"negative"`
}

// Cross-check every player rather than a handful of samples: the keyword list
// has 22 entries and a single missed substring silently changes transfer
// advice for whoever it applies to.
func TestNewsMatchesPythonForAllPlayers(t *testing.T) {
	want := loadJSON[[]newsExpectation](t, testdataPath("news_expectations.json"))
	if len(want) != 564 {
		t.Fatalf("expectations cover %d players, want 564", len(want))
	}

	var penalised, negative int
	for _, w := range want {
		p := &fpl.Player{ID: w.ID, News: w.News, NewsAdded: w.NewsAdded}

		if got := NewsPenaltyScore(p); got != w.Penalty {
			t.Errorf("player %d news=%q: penalty = %v, want %v", w.ID, w.News, got, w.Penalty)
		}
		if got := HasNegativeNews(p); got != w.Negative {
			t.Errorf("player %d news=%q: negative = %v, want %v", w.ID, w.News, got, w.Negative)
		}
		if w.Penalty != 0 {
			penalised++
		}
		if w.Negative {
			negative++
		}
	}

	// Guard against an expectations file that silently became all-zero.
	if penalised != 45 {
		t.Errorf("expectations contain %d penalised players, want 45", penalised)
	}
	if negative == 0 {
		t.Error("no negative-news players in expectations; the check is inert")
	}
}

func TestNewsPenaltyTiers(t *testing.T) {
	cases := []struct {
		news string
		want float64
	}{
		// "unknown return" outranks the generic keywords.
		{"Back injury - Unknown return date", -3.0},
		{"UNKNOWN RETURN", -3.0},
		{"Groin injury - Expected back 21 Aug", -2.0},
		// Matches on "knee" even though the text sounds reassuring.
		{"Knee injury - 75% chance of playing", -2.0},
		{"Suspended for 3 matches", -2.0},
		{"", 0.0},
		{"Joined on loan", 0.0},
	}
	for _, tc := range cases {
		p := &fpl.Player{News: tc.news}
		if got := NewsPenaltyScore(p); got != tc.want {
			t.Errorf("NewsPenaltyScore(%q) = %v, want %v", tc.news, got, tc.want)
		}
	}
}

func TestFormatNewsAge(t *testing.T) {
	base := time.Date(2026, 7, 30, 12, 0, 0, 0, time.UTC)
	at := func(d time.Duration) *string {
		s := base.Add(-d).Format(time.RFC3339Nano)
		return &s
	}

	cases := []struct {
		name  string
		added *string
		want  string
	}{
		{"nil", nil, ""},
		{"empty", ptr(""), ""},
		{"unparseable", ptr("not a date"), ""},
		{"just now", at(30 * time.Minute), "just now"},
		{"one hour", at(time.Hour), "1 hour ago"},
		{"hours", at(5 * time.Hour), "5 hours ago"},
		{"one day", at(25 * time.Hour), "1 day ago"},
		{"days", at(7 * 24 * time.Hour), "7 days ago"},
		{"29 days", at(29 * 24 * time.Hour), "29 days ago"},
		{"one month", at(31 * 24 * time.Hour), "1 month ago"},
		{"months", at(90 * 24 * time.Hour), "3 months ago"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := FormatNewsAge(tc.added, base); got != tc.want {
				t.Errorf("got %q, want %q", got, tc.want)
			}
		})
	}
}

// FPL emits timestamps with and without fractional seconds and zone suffixes.
func TestParseFPLTimeShapes(t *testing.T) {
	for _, s := range []string{
		"2026-07-23T12:01:23.272929Z",
		"2026-07-23T12:01:23Z",
		"2026-07-23T12:01:23",
		"2026-07-23T12:01:23+00:00",
		"2026-07-23",
	} {
		if _, ok := parseFPLTime(s); !ok {
			t.Errorf("failed to parse %q", s)
		}
	}
	if _, ok := parseFPLTime("nonsense"); ok {
		t.Error("parsed nonsense as a timestamp")
	}
}

func TestFormatNewsForReasoning(t *testing.T) {
	now := time.Date(2026, 7, 30, 12, 0, 0, 0, time.UTC)
	added := "2026-07-28T12:00:00Z"

	cases := []struct {
		name string
		p    *fpl.Player
		want string
	}{
		{"no news", &fpl.Player{}, ""},
		{"whitespace only", &fpl.Player{News: "   "}, ""},
		{"news without timestamp", &fpl.Player{News: "Hamstring"}, "Hamstring"},
		{"news with age", &fpl.Player{News: "Hamstring", NewsAdded: &added}, "Hamstring (2 days ago)"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := FormatNewsForReasoning(tc.p, now); got != tc.want {
				t.Errorf("got %q, want %q", got, tc.want)
			}
		})
	}
}

// News age is rendered relatively, so the engine clock must be injectable —
// otherwise any golden file containing an injured player would rot overnight.
func TestEngineClockIsInjectable(t *testing.T) {
	e := newEngine(t, "preseason")
	if e.Now().Equal(time.Now()) {
		t.Error("engine clock was not pinned by the test harness")
	}
	if !e.Now().Equal(goldenClock) {
		t.Errorf("engine clock = %v, want %v", e.Now(), goldenClock)
	}
}
